name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout actions
    - uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: run script 
      run: |
        python leetcode_generate.py
        
    # - name: Update paper list
    #   run: |
    #     cd paper_infos
    #     python generate_tables.py
        
    # - name: commit
    #   run: |
    #     git config --global user.email 1435679023@qq.com
    #     git config --global user.name marsggbo
    #     git add .
    #     git commit -m "update" -a
        
    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}